### ISSUE TITLE
No scrollbar with long pages?

### ISSUE THREAD

**Issue by ddeklerk** [ccorcos/meteor-transitioner#6]
Whenever I add anough content so it does not fit the page, there is no scrollbar. This is because of an `overflow: hidden` css-rule on the .transitioner class. When I remove the rule in Chrome's dev console, everything seems to work just fine. So, why is it in there?

**Comment by ddeklerk** [comment]
I figured out that the rule was to prevent scollbars during transitions. So in order to still have them hidden during them, but visible when not I used this bit of less.

``` less
.transitioner {
  overflow: initial;
  .velocity-animating {
    overflow: hidden;
  }
}
```

EDIT: scratch that, the scroll bars still show on a sliding transition. It does still work on a fading transition though.

hmmm... maybe this will do the trick though.

``` less
.transitioner {
  >div {
    overflow: auto;
    &.velocity-animating {
      overflow: hidden;
    }
  }
}
```
